CREATE TABLE IF NOT EXISTS account.bookingrequest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    booking_date TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_confirmed BOOLEAN NOT NULL,
    client_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    FOREIGN KEY (client_id) REFERENCES account_client(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (event_id) REFERENCES account_event(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_customuser (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    password VARCHAR(128) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS account_eventtype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS account_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_read BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    taken_at TIMESTAMP WITH TIME ZONE NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL,
    photographer_id BIGINT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES account_event(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating SMALLINT CHECK (rating >= 0),
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    client_id BIGINT NOT NULL,
    photographer_id BIGINT NOT NULL,
    FOREIGN KEY (client_id) REFERENCES account_client(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name VARCHAR(255) NOT NULL,
    organization_type VARCHAR(100) NOT NULL,
    website VARCHAR(200) NOT NULL,
    bio TEXT NOT NULL,
    profile_picture VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_hours INTEGER CHECK (duration_hours >= 0),
    price NUMERIC(10,2) NOT NULL,
    is_published BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_type_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    photographer_id BIGINT NOT NULL,
    FOREIGN KEY (event_type_id) REFERENCES account_eventtype(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (location_id) REFERENCES account_location(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    description TEXT NOT NULL,
    photo VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS account_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10,2) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE NOT NULL,
    payment_method VARCHAR(100) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL,
    is_successful BOOLEAN NOT NULL,
    booking_id BIGINT NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES account_bookingrequest(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS account_photographer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bio TEXT NOT NULL,
    portfolio_url VARCHAR(200) NOT NULL,
    expertise VARCHAR(100) NOT NULL,
    instagram_handle VARCHAR(100) NOT NULL,
    facebook_handle VARCHAR(100) NOT NULL,
    twitter_handle VARCHAR(100) NOT NULL,
    profile_picture VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
);
------------second--------------------------------------------------------
CREATE TABLE IF NOT EXISTS general.city_master (
    city_id SERIAL PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    area_code VARCHAR(50),
    country_code VARCHAR(2) NOT NULL,
    state VARCHAR(80) NOT NULL,
    population NUMERIC,
    admin VARCHAR(1),
    latitude VARCHAR(10),
    longitude VARCHAR(10),
    time_offset DOUBLE PRECISION,
    audit_date_created TIMESTAMP WITH TIME ZONE,
    audit_date_modified TIMESTAMP WITH TIME ZONE,
    audit_version INTEGER DEFAULT 0,
    audit_id SERIAL NOT NULL,
    city_synonym VARCHAR(100),
    -- location GEOGRAPHY(POINT, 4326),
    longitude_float DOUBLE PRECISION,
    latitude_float DOUBLE PRECISION,
    top_city BOOLEAN DEFAULT false,
    search_city BOOLEAN NOT NULL DEFAULT false,
    seo_city_id INTEGER,
    covid_zone VARCHAR(50),
    hindi_city VARCHAR(150),
    city_hi TEXT,
    state_hi TEXT,
    city_tier INTEGER,
    FOREIGN KEY (state, country_code) REFERENCES general.country_states(state, country_code) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS general.country_master (
    country_code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    isd_code INTEGER,
    cr_price NUMERIC(10,2),
    cr_price_old NUMERIC(10,2),
    continent VARCHAR(50),
    record_type VARCHAR(30) NOT NULL DEFAULT 'COUNTRY',
    im_contact BOOLEAN DEFAULT false,
    sms_allowed BOOLEAN DEFAULT true,
    neighbour_countries TEXT[],
    name_hi TEXT
);

CREATE TABLE IF NOT EXISTS general.country_states (
    state VARCHAR(80) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    state_abbrev VARCHAR(10),
    state_id SERIAL PRIMARY KEY,
    zone VARCHAR(100),
    gst_state_code INTEGER,
    alpha_code VARCHAR(7),
    state_hi TEXT,
    for_gst BOOLEAN DEFAULT true,
    FOREIGN KEY (country_code) REFERENCES general.country_master(country_code)
);

CREATE TABLE IF NOT EXISTS general.area_master (
    area_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    area_code VARCHAR(6) NOT NULL,
    city_id INTEGER,
    address_matched INTEGER,
    test_col INTEGER,
    UNIQUE (upper(TRIM(name)), city_id),
    CHECK (strpos(name, '"') = 0),
    FOREIGN KEY (city_id) REFERENCES general.city_master(city_id)
);

CREATE TABLE IF NOT EXISTS general.pincode_master (
    office_name VARCHAR(100),
    pincode INTEGER,
    office_type VARCHAR(10),
    delivery_status VARCHAR(100),
    division_name VARCHAR(200),
    region_name VARCHAR(100),
    circle_name VARCHAR(100),
    taluk_name VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode_id SERIAL PRIMARY KEY,
    city_id INTEGER NOT NULL,
    area_id INTEGER,
    office_name_short VARCHAR(100),
    FOREIGN KEY (area_id) REFERENCES general.area_master(area_id),
    FOREIGN KEY (city_id) REFERENCES general.city_master(city_id) ON UPDATE CASCADE
);


DROP TABLE IF EXISTS account_bookingrequest CASCADE;
DROP TABLE IF EXISTS account_customuser CASCADE;
DROP TABLE IF EXISTS account_eventtype CASCADE;
DROP TABLE IF EXISTS account_notification CASCADE;
DROP TABLE IF EXISTS account_photo CASCADE;
DROP TABLE IF EXISTS account_review CASCADE;
DROP TABLE IF EXISTS account_client CASCADE;
DROP TABLE IF EXISTS account_event CASCADE;
DROP TABLE IF EXISTS account_location CASCADE;
DROP TABLE IF EXISTS account_payment CASCADE;
DROP TABLE IF EXISTS account_photographer CASCADE;

\d general.area_master
\d general.city_master
\d general.country_master
\d general.country_states
\d general.pincode_master

also share same below table :
photo_studio_dev=> \d general.area_master

                                              Table "general.area_master"
     Column      |          Type          | Collation | Nullable |                       Default
-----------------+------------------------+-----------+----------+------------------------------------------------------
 area_id         | integer                |           | not null | nextval('general.area_master_area_id_seq'::regclass)
 name            | character varying(100) |           | not null |
 area_code       | character varying(6)   |           | not null |
 city_id         | integer                |           |          |
 address_matched | integer                |           |          |
 test_col        | integer                |           |          |
Indexes:
    "area_master_pkey_area_id" PRIMARY KEY, btree (area_id)
    "area_master_uniq_city_name" UNIQUE, btree (upper(btrim(name::text)), city_id)
Check constraints:
    "area_master_name" CHECK (strpos(name::text, '"'::text) = 0)
Foreign-key constraints:
    "area_master_city_id_fkey" FOREIGN KEY (city_id) REFERENCES general.city_master(city_id)
Referenced by:
    TABLE "general.pincode_master" CONSTRAINT "pincode_master_area_id_fkey" FOREIGN KEY (area_id) REFERENCES general.area_master(area_id)

photo_studio_dev=> \d general.city_master
photo_studio_dev=>
photo_studio_dev=> \d general.area_master

                                              Table "general.area_master"
     Column      |          Type          | Collation | Nullable |                       Default
-----------------+------------------------+-----------+----------+------------------------------------------------------
 area_id         | integer                |           | not null | nextval('general.area_master_area_id_seq'::regclass)
 name            | character varying(100) |           | not null |
 area_code       | character varying(6)   |           | not null |
 city_id         | integer                |           |          |
 address_matched | integer                |           |          |
 test_col        | integer                |           |          |
Indexes:
    "area_master_pkey_area_id" PRIMARY KEY, btree (area_id)
    "area_master_uniq_city_name" UNIQUE, btree (upper(btrim(name::text)), city_id)
Check constraints:
    "area_master_name" CHECK (strpos(name::text, '"'::text) = 0)
Foreign-key constraints:
    "area_master_city_id_fkey" FOREIGN KEY (city_id) REFERENCES general.city_master(city_id)
Referenced by:
    TABLE "general.pincode_master" CONSTRAINT "pincode_master_area_id_fkey" FOREIGN KEY (area_id) REFERENCES general.area_master(area_id)

photo_studio_dev=> \d general.city_master
                                                  Table "general.city_master"
       Column        |           Type           | Collation | Nullable |                        Default
---------------------+--------------------------+-----------+----------+-------------------------------------------------------
 city_id             | integer                  |           | not null | nextval('general.city_master_city_id_seq'::regclass)
 city                | character varying(100)   |           | not null |
 area_code           | character varying(50)    |           |          |
 country_code        | character varying(2)     |           | not null |
 state               | character varying(80)    |           | not null |
 population          | numeric                  |           |          |
 admin               | character varying(1)     |           |          |
 latitude            | character varying(10)    |           |          |
 longitude           | character varying(10)    |           |          |
 time_offset         | double precision         |           |          |
 audit_date_created  | timestamp with time zone |           |          |
 audit_date_modified | timestamp with time zone |           |          |
 audit_version       | integer                  |           |          | 0
 audit_id            | integer                  |           | not null | nextval('general.city_master_audit_id_seq'::regclass)
 city_synonym        | character varying(100)   |           |          |
 location            | geography(Point,4326)    |           |          |
 longitude_float     | double precision         |           |          |
 latitude_float      | double precision         |           |          |
 top_city            | boolean                  |           |          | false
 search_city         | boolean                  |           | not null | false
 seo_city_id         | integer                  |           |          |
 covid_zone          | character varying(50)    |           |          |
 hindi_city          | character varying(150)   |           |          |
 city_hi             | text                     |           |          |
 state_hi            | text                     |           |          |
 city_tier           | integer                  |           |          |
Indexes:
    "city_master_pkey_city_id" PRIMARY KEY, btree (city_id)
    "city_master_city_synonym" btree (city_synonym)
    "city_master_covid_zone" btree (covid_zone)
    "city_master_location_idx" gist (location)
    "city_master_search_city" btree (search_city)
    "city_master_state_country_code_fkindex" btree (state, country_code)
    "city_master_time_offset" btree (time_offset)
    "city_master_uniq_city_state_country_code" UNIQUE CONSTRAINT, btree (city, state, country_code)
    "cm_l_city" btree (lower(city::text))
    "cm_l_state" btree (lower(state::text))
Foreign-key constraints:
    "city_master_fkey_state_country_code" FOREIGN KEY (state, country_code) REFERENCES general.country_states(state, country_code) MATCH FULL ON UPDATE CASCADE
Referenced by:
    TABLE "general.area_master" CONSTRAINT "area_master_city_id_fkey" FOREIGN KEY (city_id) REFERENCES general.city_master(city_id)
    TABLE "general.pincode_master" CONSTRAINT "pincode_master_city_id_fkey" FOREIGN KEY (city_id) REFERENCES general.city_master(city_id) ON UPDATE CASCADE

photo_studio_dev=> \d general.country_master
                                   Table "general.country_master"
       Column        |          Type          | Collation | Nullable |           Default
---------------------+------------------------+-----------+----------+------------------------------
 country_code        | character varying(2)   |           | not null |
 name                | character varying(100) |           | not null |
 risk_level          | character varying(20)  |           | not null |
 isd_code            | integer                |           |          |
 cr_price            | numeric(10,2)          |           |          |
 cr_price_old        | numeric(10,2)          |           |          |
 continent           | character varying(50)  |           |          |
 record_type         | character varying(30)  |           | not null | 'COUNTRY'::character varying
 im_contact          | boolean                |           |          | false
 sms_allowed         | boolean                |           |          | true
 neighbour_countries | text[]                 |           |          |
 name_hi             | text                   |           |          |
Indexes:
    "country_master_pkey_country_code" PRIMARY KEY, btree (country_code)
    "country_master_lower_country" btree (lower(name::text))
    "country_master_uniq_name" UNIQUE CONSTRAINT, btree (name)
Referenced by:
    TABLE "general.country_states" CONSTRAINT "country_states_fkey_country_code" FOREIGN KEY (country_code) REFERENCES general.country_master(country_code)

photo_studio_dev=> \d general.country_states
                                              Table "general.country_states"
     Column     |          Type          | Collation | Nullable |                         Default
----------------+------------------------+-----------+----------+----------------------------------------------------------
 state          | character varying(80)  |           | not null |
 country_code   | character varying(2)   |           | not null |
 state_abbrev   | character varying(10)  |           |          |
 state_id       | integer                |           | not null | nextval('general.country_states_state_id_seq'::regclass)
 zone           | character varying(100) |           |          |
 gst_state_code | integer                |           |          |
 alpha_code     | character varying(7)   |           |          |
 state_hi       | text                   |           |          |
 for_gst        | boolean                |           |          | true
Indexes:
    "country_states_pkey_state_country_code" PRIMARY KEY, btree (state, country_code)
    "country_states_country_code_fkindex" btree (country_code)
    "uniq_state_id" UNIQUE CONSTRAINT, btree (state_id)
Foreign-key constraints:
    "country_states_fkey_country_code" FOREIGN KEY (country_code) REFERENCES general.country_master(country_code)
Referenced by:
    TABLE "general.city_master" CONSTRAINT "city_master_fkey_state_country_code" FOREIGN KEY (state, country_code) REFERENCES general.country_states(state, country_code) MATCH FULL ON UPDATE CASCADE

photo_studio_dev=> \d general.pincode_master
                                                 Table "general.pincode_master"
      Column       |          Type          | Collation | Nullable |                          Default
-------------------+------------------------+-----------+----------+------------------------------------------------------------
 office_name       | character varying(100) |           |          |
 pincode           | integer                |           |          |
 office_type       | character varying(10)  |           |          |
 delivery_status   | character varying(100) |           |          |
 division_name     | character varying(200) |           |          |
 region_name       | character varying(100) |           |          |
 circle_name       | character varying(100) |           |          |
 taluk_name        | character varying(100) |           |          |
 city              | character varying(100) |           |          |
 state             | character varying(100) |           |          |
 pincode_id        | integer                |           | not null | nextval('general.pincode_master_pincode_id_seq'::regclass)
 city_id           | integer                |           | not null |
 area_id           | integer                |           |          |
 office_name_short | character varying(100) |           |          |
Indexes:
    "pincode_master_pkey" PRIMARY KEY, btree (pincode_id)
    "pincode_master_area_id" btree (area_id)
    "pincode_master_city" btree (city)
    "pincode_master_city_id" btree (city_id)
    "pincode_master_pincode" btree (pincode)
    "pincode_master_state" btree (state)
Foreign-key constraints:
    "pincode_master_area_id_fkey" FOREIGN KEY (area_id) REFERENCES general.area_master(area_id)
    "pincode_master_city_id_fkey" FOREIGN KEY (city_id) REFERENCES general.city_master(city_id) ON UPDATE CASCADE

photo_studio_dev=>


\d account_bookingrequest
\d account_customuser
\d account_eventtype
\d account_notification
\d account_photo
\d account_review
\d account_client
\d account_event
\d account_location
\d account_payment
\d account_photographer


below my table description can you share same table create sql :
photo_studio_dev=> \e
                               Table "public.account_bookingrequest"
    Column    |           Type           | Collation | Nullable |             Default
--------------+--------------------------+-----------+----------+----------------------------------
 id           | bigint                   |           | not null | generated by default as identity
 status       | character varying(20)    |           | not null |
 message      | text                     |           | not null |
 booking_date | timestamp with time zone |           | not null |
 updated_at   | timestamp with time zone |           | not null |
 is_confirmed | boolean                  |           | not null |
 client_id    | bigint                   |           | not null |
 event_id     | bigint                   |           | not null |
Indexes:
    "account_bookingrequest_pkey" PRIMARY KEY, btree (id)
    "account_bookingrequest_client_id_cfc743f4" btree (client_id)
    "account_bookingrequest_event_id_875ba078" btree (event_id)
Foreign-key constraints:
    "account_bookingrequest_client_id_cfc743f4_fk_account_client_id" FOREIGN KEY (client_id) REFERENCES account_client(id) DEFERRABLE INITIALLY DEFERRED
    "account_bookingrequest_event_id_875ba078_fk_account_event_id" FOREIGN KEY (event_id) REFERENCES account_event(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "account_payment" CONSTRAINT "account_payment_booking_id_de9d3233_fk_account_b" FOREIGN KEY (booking_id) REFERENCES account_bookingrequest(id) DEFERRABLE INITIALLY DEFERRED

                                Table "public.account_customuser"
    Column    |          Type          | Collation | Nullable |             Default
--------------+------------------------+-----------+----------+----------------------------------
 id           | bigint                 |           | not null | generated by default as identity
 first_name   | character varying(100) |           | not null |
 last_name    | character varying(100) |           | not null |
 email        | character varying(254) |           | not null |
 phone_number | character varying(15)  |           | not null |
 address      | character varying(255) |           | not null |
 city         | character varying(100) |           | not null |
 state        | character varying(100) |           | not null |
 zip_code     | character varying(10)  |           | not null |
 password     | character varying(128) |           | not null |
Indexes:
    "account_customuser_pkey" PRIMARY KEY, btree (id)
    "account_customuser_email_a15d8618_like" btree (email varchar_pattern_ops)
    "account_customuser_email_key" UNIQUE CONSTRAINT, btree (email)
Referenced by:
    TABLE "account_client" CONSTRAINT "account_client_user_id_b7da2004_fk_account_customuser_id" FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "account_notification" CONSTRAINT "account_notification_user_id_520fbbdd_fk_account_customuser_id" FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "account_photographer" CONSTRAINT "account_photographer_user_id_27266b8e_fk_account_customuser_id" FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED

                             Table "public.account_eventtype"
 Column |          Type          | Collation | Nullable |             Default
--------+------------------------+-----------+----------+----------------------------------
 id     | bigint                 |           | not null | generated by default as identity
 name   | character varying(100) |           | not null |
Indexes:
    "account_eventtype_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "account_event" CONSTRAINT "account_event_event_type_id_51463ff5_fk_account_eventtype_id" FOREIGN KEY (event_type_id) REFERENCES account_eventtype(id) DEFERRABLE INITIALLY DEFERRED

                               Table "public.account_notification"
   Column   |           Type           | Collation | Nullable |             Default
------------+--------------------------+-----------+----------+----------------------------------
 id         | bigint                   |           | not null | generated by default as identity
 message    | text                     |           | not null |
 created_at | timestamp with time zone |           | not null |
 is_read    | boolean                  |           | not null |
 user_id    | bigint                   |           | not null |
Indexes:
    "account_notification_pkey" PRIMARY KEY, btree (id)
    "account_notification_user_id_520fbbdd" btree (user_id)
Foreign-key constraints:
    "account_notification_user_id_520fbbdd_fk_account_customuser_id" FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED

                                     Table "public.account_photo"
     Column      |           Type           | Collation | Nullable |             Default
-----------------+--------------------------+-----------+----------+----------------------------------
 id              | bigint                   |           | not null | generated by default as identity
 image           | character varying(100)   |           | not null |
 description     | text                     |           | not null |
 taken_at        | timestamp with time zone |           | not null |
 uploaded_at     | timestamp with time zone |           | not null |
 event_id        | bigint                   |           | not null |
 photographer_id | bigint                   |           | not null |
Indexes:
    "account_photo_pkey" PRIMARY KEY, btree (id)
    "account_photo_event_id_f3de5033" btree (event_id)
    "account_photo_photographer_id_9ad77375" btree (photographer_id)
Foreign-key constraints:
    "account_photo_event_id_f3de5033_fk_account_event_id" FOREIGN KEY (event_id) REFERENCES account_event(id) DEFERRABLE INITIALLY DEFERRED
    "account_photo_photographer_id_9ad77375_fk_account_p" FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED

                                    Table "public.account_review"
     Column      |           Type           | Collation | Nullable |             Default
-----------------+--------------------------+-----------+----------+----------------------------------
 id              | bigint                   |           | not null | generated by default as identity
 rating          | smallint                 |           | not null |
 comment         | text                     |           | not null |
 created_at      | timestamp with time zone |           | not null |
 updated_at      | timestamp with time zone |           | not null |
 client_id       | bigint                   |           | not null |
 photographer_id | bigint                   |           | not null |
Indexes:
    "account_review_pkey" PRIMARY KEY, btree (id)
    "account_review_client_id_ec752899" btree (client_id)
    "account_review_photographer_id_0b2b1db8" btree (photographer_id)
Check constraints:
    "account_review_rating_check" CHECK (rating >= 0)
Foreign-key constraints:
    "account_review_client_id_ec752899_fk_account_client_id" FOREIGN KEY (client_id) REFERENCES account_client(id) DEFERRABLE INITIALLY DEFERRED
    "account_review_photographer_id_0b2b1db8_fk_account_p" FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED

                                    Table "public.account_client"
      Column       |          Type          | Collation | Nullable |             Default
-------------------+------------------------+-----------+----------+----------------------------------
 id                | bigint                 |           | not null | generated by default as identity
 organization_name | character varying(255) |           | not null |
 organization_type | character varying(100) |           | not null |
 website           | character varying(200) |           | not null |
 bio               | text                   |           | not null |
 profile_picture   | character varying(100) |           | not null |
 user_id           | bigint                 |           | not null |
Indexes:
    "account_client_pkey" PRIMARY KEY, btree (id)
    "account_client_user_id_key" UNIQUE CONSTRAINT, btree (user_id)
Foreign-key constraints:
    "account_client_user_id_b7da2004_fk_account_customuser_id" FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "account_bookingrequest" CONSTRAINT "account_bookingrequest_client_id_cfc743f4_fk_account_client_id" FOREIGN KEY (client_id) REFERENCES account_client(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "account_review" CONSTRAINT "account_review_client_id_ec752899_fk_account_client_id" FOREIGN KEY (client_id) REFERENCES account_client(id) DEFERRABLE INITIALLY DEFERRED

                                     Table "public.account_event"
     Column      |           Type           | Collation | Nullable |             Default
-----------------+--------------------------+-----------+----------+----------------------------------
 id              | bigint                   |           | not null | generated by default as identity
 title           | character varying(255)   |           | not null |
 description     | text                     |           | not null |
 date            | timestamp with time zone |           | not null |
 duration_hours  | integer                  |           | not null |
 price           | numeric(10,2)            |           | not null |
 is_published    | boolean                  |           | not null |
 created_at      | timestamp with time zone |           | not null |
 event_type_id   | bigint                   |           | not null |
 location_id     | bigint                   |           | not null |
 photographer_id | bigint                   |           | not null |
Indexes:
    "account_event_pkey" PRIMARY KEY, btree (id)
    "account_event_event_type_id_51463ff5" btree (event_type_id)
    "account_event_location_id_9e4ae6c5" btree (location_id)
    "account_event_photographer_id_9f4db358" btree (photographer_id)
Check constraints:
    "account_event_duration_hours_check" CHECK (duration_hours >= 0)
Foreign-key constraints:
    "account_event_event_type_id_51463ff5_fk_account_eventtype_id" FOREIGN KEY (event_type_id) REFERENCES account_eventtype(id) DEFERRABLE INITIALLY DEFERRED
    "account_event_location_id_9e4ae6c5_fk_account_location_id" FOREIGN KEY (location_id) REFERENCES account_location(id) DEFERRABLE INITIALLY DEFERRED
    "account_event_photographer_id_9f4db358_fk_account_p" FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "account_bookingrequest" CONSTRAINT "account_bookingrequest_event_id_875ba078_fk_account_event_id" FOREIGN KEY (event_id) REFERENCES account_event(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "account_photo" CONSTRAINT "account_photo_event_id_f3de5033_fk_account_event_id" FOREIGN KEY (event_id) REFERENCES account_event(id) DEFERRABLE INITIALLY DEFERRED

                                Table "public.account_location"
   Column    |          Type          | Collation | Nullable |             Default
-------------+------------------------+-----------+----------+----------------------------------
 id          | bigint                 |           | not null | generated by default as identity
 name        | character varying(100) |           | not null |
 address     | character varying(255) |           | not null |
 city        | character varying(100) |           | not null |
 state       | character varying(100) |           | not null |
 zip_code    | character varying(10)  |           | not null |
 latitude    | numeric(9,6)           |           | not null |
 longitude   | numeric(9,6)           |           | not null |
 description | text                   |           | not null |
 photo       | character varying(100) |           | not null |
Indexes:
    "account_location_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "account_event" CONSTRAINT "account_event_location_id_9e4ae6c5_fk_account_location_id" FOREIGN KEY (location_id) REFERENCES account_location(id) DEFERRABLE INITIALLY DEFERRED

                                   Table "public.account_payment"
     Column     |           Type           | Collation | Nullable |             Default
----------------+--------------------------+-----------+----------+----------------------------------
 id             | bigint                   |           | not null | generated by default as identity
 amount         | numeric(10,2)            |           | not null |
 payment_date   | timestamp with time zone |           | not null |
 payment_method | character varying(100)   |           | not null |
 transaction_id | character varying(100)   |           | not null |
 is_successful  | boolean                  |           | not null |
 booking_id     | bigint                   |           | not null |
Indexes:
    "account_payment_pkey" PRIMARY KEY, btree (id)
    "account_payment_booking_id_de9d3233" btree (booking_id)
Foreign-key constraints:
    "account_payment_booking_id_de9d3233_fk_account_b" FOREIGN KEY (booking_id) REFERENCES account_bookingrequest(id) DEFERRABLE INITIALLY DEFERRED

                                 Table "public.account_photographer"
      Column      |          Type          | Collation | Nullable |             Default
------------------+------------------------+-----------+----------+----------------------------------
 id               | bigint                 |           | not null | generated by default as identity
 bio              | text                   |           | not null |
 portfolio_url    | character varying(200) |           | not null |
 expertise        | character varying(100) |           | not null |
 instagram_handle | character varying(100) |           | not null |
 facebook_handle  | character varying(100) |           | not null |
 twitter_handle   | character varying(100) |           | not null |
 profile_picture  | character varying(100) |           | not null |
 user_id          | bigint                 |           | not null |
Indexes:
    "account_photographer_pkey" PRIMARY KEY, btree (id)
    "account_photographer_user_id_key" UNIQUE CONSTRAINT, btree (user_id)
Foreign-key constraints:
    "account_photographer_user_id_27266b8e_fk_account_customuser_id" FOREIGN KEY (user_id) REFERENCES account_customuser(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "account_event" CONSTRAINT "account_event_photographer_id_9f4db358_fk_account_p" FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "account_photo" CONSTRAINT "account_photo_photographer_id_9ad77375_fk_account_p" FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "account_review" CONSTRAINT "account_review_photographer_id_0b2b1db8_fk_account_p" FOREIGN KEY (photographer_id) REFERENCES account_photographer(id) DEFERRABLE INITIALLY DEFERRED

photo_studio_dev=>
